// <auto-generated />
namespace PipelineMLWeb.DataContexts.PipelineMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170304Addingschemas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170304Addingschemas));
        
        string IMigrationMetadata.Id
        {
            get { return "201703041502409_2017.03.04 Adding schemas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
