// <auto-generated />
namespace PipelineMLWeb.DataContexts.PipelineMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170112Third : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170112Third));
        
        string IMigrationMetadata.Id
        {
            get { return "201701122203382_2017.01.12 Third"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
